# Generated by Django 5.2.4 on 2025-07-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
