# Generated by Django 5.2.4 on 2025-07-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(db_index=True, max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sales_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_order_count', models.IntegerField(default=0)),
                ('online_order_count', models.IntegerField(default=0)),
                ('walkin_order_count', models.IntegerField(default=0)),
                ('avg_items_per_order', models.FloatField(default=0.0)),
                ('dish_performance', models.JSONField(default=list)),
                ('avg_hourly_orders', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('report_type', 'start_date', 'end_date')},
            },
        ),
    ]
