# Generated by Django 5.2.4 on 2025-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='recommendation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='analytics',
            name='recommendation_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
