# Generated by Django 5.2.4 on 2025-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analytics_recommendation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
