# .github/workflows/main_luks-backend-api.yml

name: Build and deploy Python app to Azure Web App - luks-backend-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2 # Using v2 which works well with publish-profile
        with:
          app-name: "luks-backend-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          # The following lines enable the on-server build and pass our secrets
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          app-settings-json: |
            [
              { "name": "DJANGO_SECRET_KEY", "value": "${{ secrets.DJANGO_SECRET_KEY }}", "slotSetting": false },
              { "name": "DATABASE_URL", "value": "${{ secrets.DATABASE_URL }}", "slotSetting": false },
              { "name": "DJANGO_DEBUG", "value": "${{ secrets.DJANGO_DEBUG }}", "slotSetting": false }
            ]
