# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - luksbygoodchoice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: luksrestaurantacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_1D470A439D844738A9EAABF61E0B6BB8 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_33002F9BE49A405BA92EEE432A7FBEBF }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: luksrestaurantacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_1D470A439D844738A9EAABF61E0B6BB8 }}/luks-restaurant-backend:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_11A9DC39CA5D4096A7CCC244DC6720E3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B935375135AB4CD09FF886F597E3C16A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_999E9CBBE016499C9C9EE48BFD74A59F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
        app-name: "luksbygoodchoice"
        slot-name: "Production"
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_... }}
        images: "${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        startup-command: "gunicorn --chdir /app -w 4 backend.wsgi:application"
